import { useEffect, useRef, useState } from 'react';

const secondsSince = (start) => Math.max(1, Math.round((Date.now() - start) / 1000));
const record = (onComplete, game, start, score, accuracy) => onComplete(game.name, game.category, Math.max(0, Math.min(1000, Math.round(score))), Math.max(0, Math.min(100, Math.round(accuracy))), secondsSince(start));
function CanvasShell({ game, onExit, eyebrow, children }) {
  return <main className="cognitive-game-screen arcade-screen"><header className="cognitive-game-topbar"><button type="button" className="btn-cancel" onClick={onExit}><i className="ph ph-arrow-left"></i> Exit game</button><div className="cognitive-game-top-meta"><span>{eyebrow}</span><span>CANVAS ARCADE</span></div><span className="cognitive-game-score"><i className={`ph-fill ${game.icon}`}></i> {game.name}</span></header>{children}</main>;
}

function KnifeShow({ game, onComplete, onExit }) {
  const canvasRef = useRef(null); const state = useRef(null); const [hits, setHits] = useState(0); const [misses, setMisses] = useState(0); const [best, setBest] = useState(() => Number(localStorage.getItem('gamepal-knife-best')) || 0); const [ended, setEnded] = useState(false); const startRef = useRef(0); const completeRef = useRef(false); const fireRef = useRef(null);
  useEffect(() => { startRef.current = Date.now(); const canvas = canvasRef.current; const ctx = canvas.getContext('2d'); state.current = { angle: 0, speed: 1.45, spinDirection: 1, spinTimer: 0, knives: [], projectile: null, particles: [], flash: 0, shake: 0, misses: 0, hits: 0, last: 0, finished: false }; let raf;
    const fire = () => { const s = state.current; if (s && !s.finished && !s.projectile) s.projectile = { y: 490, prev: 490 }; }; fireRef.current = fire;
    const drawKnife = (x, y, angle, color = '#dce8f7', scale = 1) => { ctx.save(); ctx.translate(x, y); ctx.rotate(angle); ctx.scale(scale, scale); ctx.fillStyle = '#e8eef5'; ctx.beginPath(); ctx.moveTo(-4, 4); ctx.lineTo(4, 4); ctx.lineTo(2, -29); ctx.lineTo(0, -38); ctx.lineTo(-2, -29); ctx.closePath(); ctx.fill(); ctx.fillStyle = color; ctx.fillRect(-5, 3, 10, 17); ctx.fillStyle = '#f59e0b'; ctx.fillRect(-5, 11, 10, 3); ctx.restore(); };
    const draw = (time) => { const s = state.current; if (!s) return; const dt = Math.min(.035, (time - (s.last || time)) / 1000); s.last = time; if (!s.finished) { s.spinTimer += dt; if (s.spinTimer > 4.5) { s.spinTimer = 0; s.spinDirection *= -1; } s.angle += s.speed * s.spinDirection * dt * (1 + Math.min(1.1, s.hits * .06)); if (s.projectile) { s.projectile.prev = s.projectile.y; s.projectile.y -= 1040 * dt; if (s.projectile.y <= 300) { const landing = Math.PI; const impact = ((landing - s.angle) % (Math.PI * 2) + Math.PI * 2) % (Math.PI * 2); const collision = s.knives.some((knife) => { let diff = Math.abs(knife - impact); return Math.min(diff, Math.PI * 2 - diff) < .23; }); if (collision) { s.misses += 1; s.shake = 14; s.flash = 1; setMisses(s.misses); for (let i = 0; i < 12; i += 1) s.particles.push({ x: 400, y: 290, vx: (Math.random() - .5) * 300, vy: -Math.random() * 230, life: .8 }); if (s.misses >= 3) s.finished = true; } else { s.knives.push(impact); s.hits += 1; s.shake = 4; s.flash = .8; setHits(s.hits); setBest((old) => { const next = Math.max(old, s.hits); try { localStorage.setItem('gamepal-knife-best', String(next)); } catch { /* Ignore unavailable storage. */ } return next; }); for (let i = 0; i < 9; i += 1) s.particles.push({ x: 400, y: 290, vx: (Math.random() - .5) * 180, vy: -Math.random() * 150, life: .55 }); if (s.hits >= 12) s.finished = true; } s.projectile = null; } } }
      const shakeX = s.shake ? (Math.random() - .5) * s.shake : 0; s.shake *= .86; ctx.save(); ctx.translate(shakeX, 0); ctx.fillStyle = '#07111f'; ctx.fillRect(0, 0, 800, 540); const bg = ctx.createRadialGradient(400, 200, 30, 400, 230, 480); bg.addColorStop(0, '#213147'); bg.addColorStop(1, '#07111f'); ctx.fillStyle = bg; ctx.fillRect(0, 0, 800, 540);
      ctx.fillStyle = '#c8d7e7'; ctx.font = '700 15px system-ui'; ctx.textAlign = 'left'; ctx.fillText(`ARENA ${Math.floor(s.hits / 4) + 1}`, 28, 38); ctx.textAlign = 'right'; ctx.fillText(`${s.hits} / 12`, 770, 38);
      ctx.save(); ctx.translate(400, 192); ctx.rotate(s.angle); ctx.fillStyle = s.flash > .03 ? '#dfa361' : '#995f37'; ctx.beginPath(); ctx.arc(0, 0, 92, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#663d28'; ctx.lineWidth = 3; for (let ring = 0; ring < 5; ring += 1) { ctx.beginPath(); ctx.ellipse(0, 0, 17 + ring * 15, 10 + ring * 14, ring * .25, .1, Math.PI * 1.88); ctx.stroke(); } ctx.fillStyle = '#603e29'; ctx.beginPath(); ctx.arc(0, 0, 15, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#e7c28f'; ctx.beginPath(); ctx.arc(3, -3, 5, 0, Math.PI * 2); ctx.fill(); s.knives.forEach((angle) => drawKnife(Math.sin(angle) * 92, -Math.cos(angle) * 92, angle)); ctx.restore();
      if (s.projectile) drawKnife(400, s.projectile.y, 0); ctx.fillStyle = '#a9c1d7'; ctx.fillRect(305, 504, 190, 3); s.particles = s.particles.filter((p) => p.life > 0); s.particles.forEach((p) => { p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 210 * dt; p.life -= dt; ctx.globalAlpha = Math.max(0, p.life * 1.7); ctx.fillStyle = '#ffc35c'; ctx.fillRect(p.x, p.y, 4, 4); }); ctx.globalAlpha = 1; s.flash *= .89; ctx.restore();
      if (s.finished && !completeRef.current) { completeRef.current = true; setEnded(true); const score = s.hits / 12 * 1000 - s.misses * 35; record(onComplete, game, startRef.current, score, s.hits / Math.max(1, s.hits + s.misses) * 100); }
      raf = requestAnimationFrame(draw);
    }; raf = requestAnimationFrame(draw); const key = (event) => { if (event.code === 'Space' || event.key === 'Enter') { event.preventDefault(); fire(); } }; window.addEventListener('keydown', key); return () => { cancelAnimationFrame(raf); window.removeEventListener('keydown', key); };
  }, [game, onComplete]);
  return <CanvasShell game={game} onExit={onExit} eyebrow="PRECISION THROW"><section className="arcade-card canvas-arcade-card"><div className="arcade-heading"><div><p className="eyebrow">TIMING ARENA · TARGET CHANGES DIRECTION</p><h1>Wait for the opening.</h1><p>Hit the target between the blades. Clean hits increase the spin speed.</p></div><div className="arcade-score-pills"><span><small>HITS</small><b>{hits}/12</b></span><span><small>COLLISIONS</small><b>{misses}/3</b></span><span><small>BEST</small><b>{best}</b></span></div></div><canvas ref={canvasRef} className="arcade-canvas knife-canvas" width="800" height="540" onPointerDown={() => fireRef.current?.()} aria-label="Knife Show rotating target"/><div className="arcade-game-actions"><button type="button" className="gamepal-primary-action" onClick={() => fireRef.current?.()} disabled={ended}><i className="ph-fill ph-target"></i> Throw blade</button><span className="arcade-feedback">Tap arena or press Space</span></div>{ended && <p className="arcade-feedback">{hits >= 12 ? 'Target cleared. Clean work.' : `Run over · ${hits} clean hits.`}</p>}</section></CanvasShell>;
}

function DinoRunner({ game, onComplete, onExit }) {
  const canvasRef = useRef(null); const world = useRef(null); const [distance, setDistance] = useState(0); const [best, setBest] = useState(() => Number(localStorage.getItem('gamepal-dino-best')) || 0); const bestRef = useRef(0); const [ended, setEnded] = useState(false); const startRef = useRef(0); const completeRef = useRef(false); const jumpRef = useRef(null); const duckRef = useRef(false);
  useEffect(() => { startRef.current = Date.now(); bestRef.current = Number(localStorage.getItem('gamepal-dino-best')) || 0; const canvas = canvasRef.current; const ctx = canvas.getContext('2d'); world.current = { y: 0, vy: 0, jumping: false, obstacles: [], distance: 0, spawn: 0, time: 0, night: false, over: false, last: 0 }; let raf; let frame = 0;
    const jump = () => { const s = world.current; if (s && !s.jumping && !s.over) { s.vy = -610; s.jumping = true; } }; jumpRef.current = jump;
    const pixels = (x, y, width, height, color) => { ctx.fillStyle = color; ctx.fillRect(Math.round(x), Math.round(y), width, height); };
    const draw = (time) => { const s = world.current; const w = canvas.width; const h = canvas.height; const dt = Math.min(.035, (time - (s.last || time)) / 1000); s.last = time; s.time += dt; const speed = 300 + Math.min(260, s.distance * .4); if (!s.over) { s.distance += dt * speed / 10; s.spawn += dt; if (s.spawn > Math.max(.8, 1.45 - s.distance / 1500)) { const bird = s.distance > 110 && Math.random() > .58; s.obstacles.push({ x: w + 20, kind: bird ? 'bird' : 'cactus', y: bird ? 232 + Math.random() * 10 : 0, size: bird ? 42 : 32 }); s.spawn = 0; } s.y += s.vy * dt; s.vy += 1700 * dt; if (s.y >= 0) { s.y = 0; s.jumping = false; } s.obstacles.forEach((item) => { item.x -= speed * dt; }); s.obstacles = s.obstacles.filter((item) => item.x > -70); const player = { x: 128, y: 240 - s.y - (duckRef.current ? -16 : 0), w: duckRef.current ? 60 : 45, h: duckRef.current ? 30 : 48 }; const hit = s.obstacles.some((item) => { const box = item.kind === 'bird' ? { x: item.x, y: item.y, w: 38, h: 25 } : { x: item.x + 3, y: 250, w: 25, h: 39 }; return player.x + player.w - 8 > box.x + 5 && player.x + 8 < box.x + box.w && player.y + player.h - 5 > box.y + 5 && player.y + 5 < box.y + box.h; }); if (hit) s.over = true; s.night = Math.floor(s.distance / 550) % 2 === 1; }
      const dark = s.night; const fg = dark ? '#e9eef5' : '#444c56'; const bg = dark ? '#141a23' : '#fbfcfe'; ctx.fillStyle = bg; ctx.fillRect(0, 0, w, h); ctx.fillStyle = dark ? '#222d3c' : '#edf1f3'; ctx.beginPath(); ctx.arc(710, 90, 31, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = fg; ctx.font = '20px monospace'; ctx.textAlign = 'right'; ctx.fillText(`HI ${Math.max(bestRef.current, Math.floor(s.distance)).toString().padStart(5, '0')}  ${Math.floor(s.distance).toString().padStart(5, '0')}`, w - 35, 38); ctx.fillStyle = dark ? '#3b4656' : '#cbd2d8'; ctx.fillRect(0, 292, w, 2);
      for (let x = 0; x < w; x += 64) { const offset = (s.distance * 6) % 64; pixels(x - offset, 300 + (x % 13), 4, 2, dark ? '#303b4a' : '#dfe4e7'); }
      frame += 1; const dy = 246 - s.y; const duck = duckRef.current; pixels(128, duck ? dy + 14 : dy, duck ? 54 : 34, duck ? 23 : 33, fg); pixels(148, duck ? dy + 3 : dy - 11, 25, 22, fg); pixels(165, duck ? dy + 5 : dy - 8, 15, 5, bg); pixels(130, duck ? dy + 33 : dy + 27, 8, 16, fg); pixels(148, duck ? dy + 33 : dy + 26, 8, 17, fg); if (!s.jumping && !duck && frame % 12 < 6) pixels(128, dy + 39, 8, 6, bg); else if (!s.jumping && !duck) pixels(148, dy + 39, 8, 6, bg); pixels(171, duck ? dy + 17 : dy + 4, 8, 3, dark ? '#fb7185' : '#16a34a');
      s.obstacles.forEach((item) => { if (item.kind === 'cactus') { pixels(item.x + 10, 253, 12, 38, dark ? '#a6c17b' : '#47744b'); pixels(item.x + 2, 263, 10, 7, dark ? '#a6c17b' : '#47744b'); pixels(item.x + 2, 257, 5, 10, dark ? '#a6c17b' : '#47744b'); pixels(item.x + 20, 270, 10, 7, dark ? '#a6c17b' : '#47744b'); pixels(item.x + 25, 264, 5, 12, dark ? '#a6c17b' : '#47744b'); } else { pixels(item.x, item.y + 10, 34, 11, fg); pixels(item.x + 11, item.y, 15, 20, fg); pixels(item.x + 7, item.y + 14, 7, 11, bg); pixels(item.x + 27, item.y + 8, 14, 5, fg); } });
      if (Math.floor(s.distance) % 10 === 0 && !s.over) setDistance(Math.floor(s.distance));
      if (s.over && !completeRef.current) { completeRef.current = true; setEnded(true); const points = Math.floor(s.distance); const nextBest = Math.max(bestRef.current, points); bestRef.current = nextBest; setBest(nextBest); try { localStorage.setItem('gamepal-dino-best', String(nextBest)); } catch { /* Keep the result if storage is unavailable. */ } record(onComplete, game, startRef.current, Math.min(1000, points * 1.7), Math.min(99, points / 7)); }
      raf = requestAnimationFrame(draw);
    }; raf = requestAnimationFrame(draw); const down = (event) => { if ([' ', 'ArrowUp', 'w', 'W'].includes(event.key)) { event.preventDefault(); jump(); } if (['ArrowDown', 's', 'S'].includes(event.key)) duckRef.current = true; }; const up = (event) => { if (['ArrowDown', 's', 'S'].includes(event.key)) duckRef.current = false; }; window.addEventListener('keydown', down); window.addEventListener('keyup', up); return () => { cancelAnimationFrame(raf); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); };
  }, [game, onComplete]);
  return <CanvasShell game={game} onExit={onExit} eyebrow="PIXEL DESERT · ENDLESS RUN"><section className="arcade-card canvas-arcade-card"><div className="arcade-heading"><div><p className="eyebrow">T-REX SPRINT · DAY / NIGHT</p><h1>Keep the run alive.</h1><p>Jump over cacti. Hold duck below flying hazards.</p></div><div className="arcade-score-pills"><span><small>DISTANCE</small><b>{distance}</b></span><span><small>BEST</small><b>{best}</b></span></div></div><canvas ref={canvasRef} className="arcade-canvas dino-canvas" width="900" height="340" onPointerDown={() => jumpRef.current?.()} aria-label="Pixel dinosaur runner"/><div className="arcade-game-actions"><button type="button" className="gamepal-primary-action" onClick={() => jumpRef.current?.()} disabled={ended}>↑ Jump</button><button type="button" className="gamepal-secondary-action" onPointerDown={() => { duckRef.current = true; }} onPointerUp={() => { duckRef.current = false; }} onPointerLeave={() => { duckRef.current = false; }} disabled={ended}>↓ Hold to duck</button></div>{ended && <p className="arcade-feedback">Run ended at {distance}. Start another round from the results panel.</p>}</section></CanvasShell>;
}

function SnowRider({ game, onComplete, onExit }) {
  const canvasRef = useRef(null); const world = useRef(null); const [gifts, setGifts] = useState(0); const [distance, setDistance] = useState(0); const [ended, setEnded] = useState(false); const startRef = useRef(0); const completeRef = useRef(false); const moveRef = useRef(null); const jumpRef = useRef(null);
  useEffect(() => { startRef.current = Date.now(); const canvas = canvasRef.current; const ctx = canvas.getContext('2d'); world.current = { lane: 0, targetLane: 0, jump: 0, objects: [], spawn: 0, time: 0, gifts: 0, distance: 0, last: 0, over: false, snow: Array.from({ length: 90 }, () => ({ x: Math.random() * canvas.width, y: Math.random() * canvas.height, speed: 45 + Math.random() * 130 })) }; let raf;
    const move = (delta) => { const s = world.current; if (s) s.targetLane = Math.max(-1, Math.min(1, s.targetLane + delta)); }; moveRef.current = move; const jump = () => { const s = world.current; if (s && !s.over && s.jump <= 0) s.jump = 1; }; jumpRef.current = jump;
    const draw = (time) => { const s = world.current; const w = canvas.width; const h = canvas.height; const dt = Math.min(.035, (time - (s.last || time)) / 1000); s.last = time; if (!s.over) { s.time += dt; s.distance += dt * 34; s.lane += (s.targetLane - s.lane) * Math.min(1, dt * 8); s.jump = Math.max(0, s.jump - dt * 1.55); s.spawn += dt; if (s.spawn > .53) { s.objects.push({ lane: Math.floor(Math.random() * 3) - 1, z: 0, kind: Math.random() > .28 ? 'tree' : 'gift', phase: Math.random() * 5 }); s.spawn = 0; } s.objects.forEach((obj) => { obj.z += dt * (.24 + Math.min(.23, s.distance / 10000)); obj.phase += dt * 2; }); const contact = s.objects.find((obj) => obj.z > .87 && obj.z < .98 && obj.lane === Math.round(s.lane)); if (contact?.kind === 'gift') { contact.z = 2; s.gifts += 1; setGifts(s.gifts); } else if (contact?.kind === 'tree' && s.jump < .36) s.over = true; s.objects = s.objects.filter((obj) => obj.z < 1.15); if (s.time >= 45) s.over = true; }
      const sky = ctx.createLinearGradient(0, 0, 0, h); sky.addColorStop(0, '#91d5fa'); sky.addColorStop(.54, '#e5f6ff'); sky.addColorStop(1, '#cadfed'); ctx.fillStyle = sky; ctx.fillRect(0, 0, w, h); ctx.fillStyle = '#fff7df'; ctx.beginPath(); ctx.arc(735, 78, 34, 0, Math.PI * 2); ctx.fill();
      const mountain = (points, color) => { ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(points[0][0], points[0][1]); points.slice(1).forEach(([x, y]) => ctx.lineTo(x, y)); ctx.closePath(); ctx.fill(); }; mountain([[0, 250], [135, 104], [250, 232], [405, 74], [545, 231], [710, 112], [900, 246], [900, 330], [0, 330]], '#b9d5e5'); mountain([[0, 273], [166, 160], [285, 287], [456, 132], [603, 278], [780, 168], [900, 270], [900, 340], [0, 340]], '#d9e8f1');
      const roadTop = 278; ctx.fillStyle = '#f9fcff'; ctx.beginPath(); ctx.moveTo(450 - 84, roadTop); ctx.lineTo(450 + 84, roadTop); ctx.lineTo(840, h); ctx.lineTo(60, h); ctx.closePath(); ctx.fill(); ctx.strokeStyle = 'rgba(74,121,151,.3)'; ctx.lineWidth = 3; [-.33, .33].forEach((offset) => { ctx.beginPath(); ctx.moveTo(450 + offset * 84, roadTop); ctx.lineTo(450 + offset * 390, h); ctx.stroke(); });
      for (const obj of [...s.objects].sort((a, b) => a.z - b.z)) { const z = obj.z; const scale = .12 + z * 1.2; const centerX = 450 + obj.lane * (45 + z * 230); const y = roadTop + z * 215; if (obj.kind === 'gift') { ctx.save(); ctx.translate(centerX, y - Math.sin(obj.phase) * 6); ctx.scale(scale, scale); ctx.fillStyle = '#ef525b'; ctx.fillRect(-12, -20, 24, 24); ctx.fillStyle = '#ffd166'; ctx.fillRect(-3, -20, 6, 24); ctx.fillRect(-12, -11, 24, 5); ctx.restore(); } else { ctx.save(); ctx.translate(centerX, y); ctx.scale(scale, scale); ctx.fillStyle = '#164e45'; ctx.beginPath(); ctx.moveTo(0, -82); ctx.lineTo(35, -16); ctx.lineTo(16, -16); ctx.lineTo(51, 18); ctx.lineTo(-49, 18); ctx.lineTo(-16, -16); ctx.lineTo(-34, -16); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#784e39'; ctx.fillRect(-5, 15, 10, 22); ctx.restore(); } }
      s.snow.forEach((flake) => { flake.y += flake.speed * dt; flake.x -= 18 * dt; if (flake.y > h) { flake.y = -5; flake.x = Math.random() * w; } if (flake.x < 0) flake.x = w; ctx.fillStyle = 'rgba(255,255,255,.78)'; ctx.fillRect(flake.x, flake.y, 2, 2); });
      const px = 450 + s.lane * 205; const py = 455 - s.jump * 70; ctx.save(); ctx.translate(px, py); ctx.rotate(Math.sin(s.time * 4) * .035); ctx.fillStyle = 'rgba(36,59,77,.2)'; ctx.beginPath(); ctx.ellipse(0, 25, 42, 8, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#e33d52'; ctx.beginPath(); ctx.moveTo(-37, 10); ctx.lineTo(33, 10); ctx.lineTo(44, 19); ctx.lineTo(-29, 19); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#18334b'; ctx.fillRect(-8, -14, 17, 24); ctx.fillStyle = '#f0c7a4'; ctx.beginPath(); ctx.arc(0, -22, 10, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#20384e'; ctx.beginPath(); ctx.arc(0, -27, 11, Math.PI, Math.PI * 2); ctx.fill(); ctx.restore();
      ctx.fillStyle = '#17405b'; ctx.font = '700 18px system-ui'; ctx.textAlign = 'left'; ctx.fillText(`DISTANCE ${Math.floor(s.distance)} m`, 24, 35); ctx.textAlign = 'right'; ctx.fillText(`GIFTS ${s.gifts}`, 876, 35); if (Math.floor(s.distance) % 10 === 0) setDistance(Math.floor(s.distance));
      if (s.over && !completeRef.current) { completeRef.current = true; setEnded(true); const score = Math.min(1000, Math.floor((s.distance / (45 * 34)) * 700 + s.gifts * 30)); record(onComplete, game, startRef.current, score, Math.min(100, (s.distance / (45 * 34)) * 80 + s.gifts)); }
      raf = requestAnimationFrame(draw);
    }; raf = requestAnimationFrame(draw); const key = (event) => { const left = ['ArrowLeft', 'a', 'A'].includes(event.key); const right = ['ArrowRight', 'd', 'D'].includes(event.key); const up = [' ', 'ArrowUp', 'w', 'W'].includes(event.key); if (left || right || up) { event.preventDefault(); if (left) move(-1); if (right) move(1); if (up) jump(); } }; window.addEventListener('keydown', key); return () => { cancelAnimationFrame(raf); window.removeEventListener('keydown', key); };
  }, [game, onComplete]);
  return <CanvasShell game={game} onExit={onExit} eyebrow="ALPINE DESCENT · PSEUDO 3D"><section className="arcade-card canvas-arcade-card"><div className="arcade-heading"><div><p className="eyebrow">SNOW RIDER · ENDLESS SLOPE</p><h1>Carve a line down the mountain.</h1><p>Switch lanes, avoid pine trees, jump hazards, and gather gifts.</p></div><div className="arcade-score-pills"><span><small>DISTANCE</small><b>{distance} m</b></span><span><small>GIFTS</small><b>{gifts}</b></span></div></div><canvas ref={canvasRef} className="arcade-canvas snow-canvas" width="900" height="520" aria-label="Pseudo 3D alpine sled course"/><div className="arcade-game-actions"><button type="button" className="gamepal-secondary-action" onClick={() => moveRef.current?.(-1)}>← Left</button><button type="button" className="gamepal-primary-action" onClick={() => jumpRef.current?.()}>↑ Jump</button><button type="button" className="gamepal-secondary-action" onClick={() => moveRef.current?.(1)}>Right →</button></div>{ended && <p className="arcade-feedback">Descent complete · {distance} m · {gifts} gifts collected.</p>}</section></CanvasShell>;
}

const COMPONENTS = { knifeshow: KnifeShow, snowrider: SnowRider, dino: DinoRunner };
export default function CanvasSpecialMiniGame({ game, onComplete, onExit }) {
  const Game = COMPONENTS[game.id];
  return Game ? <Game game={game} onComplete={onComplete} onExit={onExit} /> : null;
}
