[package]
name = "ipcs-student-portal"
version = "1.0.0"
description = "Talenzo student portal from IPCS Global"
authors = ["IPCS Global"]
edition = "2021"

[lib]
name = "ipcs_student_portal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
